# -*- coding: utf-8 -*-
"""alternative_api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11CPogfaxdTqM6gS72a0eGVqh1jWrJQ_8
"""

import requests
import pandas as pd

URL = 'https://api.alternative.me/fng/'

params = {
    "limit": 365
}

def extract_data():
  r = requests.get(URL, params=params)
  data = r.json()
  return data

data = extract_data()
data['data']

df = pd.DataFrame(data['data'])
df

df.to_parquet('raw_fear_and_greed_idx.parquet')