# -*- coding: utf-8 -*-
"""interest_rates.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tBR88b_NMArcYAVsFKWj_vc3cHFOpg2u
"""

! pip install fredapi > /dev/null

import requests
import pandas as pd
from fredapi import Fred
from google.colab import userdata

API_KEY = userdata.get('FRED_API_KEY')

fred  = Fred(api_key=API_KEY)

interest_rates = fred.get_series('RIFSPFFNB')

df = pd.DataFrame(interest_rates)
df.to_parquet('interest_rates.parquet')

sp500 = fred.get_series('SP500')
df = pd.DataFrame(sp500)
df.to_parquet('sp500_series.parquet')

cpi = fred.get_series('CPIAUCSL')

cpi_df = pd.DataFrame(cpi)
cpi_df.to_parquet('cpi_raw.parquet')

unem_rate = fred.get_series('UNRATE')
unem_rate.plot()

unem_rate_df = pd.DataFrame(unem_rate)
unem_rate_df.to_parquet('unemp_rate.parquet')