# -*- coding: utf-8 -*-
"""transform_cpi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KduTxDXOI3iY3SADjsKdn5_HaUneYUl0
"""

import pandas as pd
import datetime as dt

df = pd.read_parquet('raw_cpi.parquet')

df.info()

df['monthly_inflation'] = (df[0].pct_change(periods=12) * 100).round(2)

get_today = dt.date.today()
df = df.loc["2000-01-01": f"{get_today.year}-{get_today.month}-01" ]

df.index.name = 'date'
df.drop(columns=0, inplace=True)

df.plot()