# -*- coding: utf-8 -*-
"""raw_prices.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nUiRV9UtoVl2rh2u4YjCC3ZtAhppBERR
"""

!pip install pyarrow

import pandas as pd
import requests
import json
import time

api_key = 'CG-ix8WhVd9TK4pQ9rPbbAMjBsj'
# btc metadata url = f'https://api.coingecko.com/api/v3/coins/bitcoin'
to_timestamp = int(time.time())
url = f'https://api.coingecko.com/api/v3/coins/bitcoin/market_chart/range'
params = {
    'vs_currency' : 'usd',
    'from' : 	1729204510,
    'to' : to_timestamp
}

def data_extract():
  try:
    r = requests.get(url, params=params ,headers={ 'x-cg-demo-api-key': api_key })
    r.raise_for_status()
    data = r.json()
    return data
  except requests.exceptions.RequestException as e:
    print(f"An error occurred: {e}")

data = data_extract()

df = pd.DataFrame(data, dtype=object)

df['date'] = [ elem[0] for elem in df['prices']]
df['date'] =  pd.to_datetime(df['date'], unit='ms')

df.set_index('date', inplace=True)

df['prices'] = [ round(elem[1], 2)  for elem in df['prices'] ]
df['market_caps'] = [ round(elem[1], 2) for elem in df['market_caps'] ]
df['total_volumes'] = [ round(elem[1], 2) for elem in df['total_volumes'] ]
df

df['prices'].plot()

df.to_parquet('raw_btc_prices.parquet')

pdf = pd.read_parquet('raw_btc_prices.parquet', columns=['date'])
pdf